# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ production, beta, stable ]

  pull_request:
    branches: [ production, beta, stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install private dependencies
      env:
        username: ${{ secrets.USERNAME }}
        secrets_token: ${{ secrets.SECRET_TOKEN }}
      run: |
        pip install git+https://$username:$secrets_token@github.com/callistoteam/iamschool.git
    - name: Test with pytest
      env: 
        API_KEY: None
        channel_id: None
      run: |
        pytest
